### ISSUE TITLE
Dice So Nice 5.0+ does not roll for attacks while RSR5e is enabled.

### ISSUE THREAD

**Issue by friction1** [MangoFVTT/fvtt-ready-set-roll-5e#472] opened 2024-08-02 13:57 UTC
Dice So Nice 4.X.X seems to work appropriately with the latest RSR for 5e, but they just released an update (now 5.0.3) and now the dice do not roll when you click on attacks for PCs or NPCs.

**Steps to Reproduce**
1. Enable DsN 5.0.3 and RSR5e 3.1.4
2. Click on an attack for any NPC or PC
3. DsN dice do not appear as expected

**Versions**
 - Module: 3.1.4
 - dnd5e: 3.3.1
 - Foundry: 12.330

**Other Modules**
Dice So Nice v 5.0.3

**Comment by Oxy949** [comment] 2024-08-03 07:59
Confirmed. Has the same issue.

**Comment by MissZerglot** [comment] 2024-08-03 14:23
Can confirm that this is also the case in V11 of foundry.

**Comment by nschoenwald** [comment] 2024-08-04 17:58
Damage dice show up if you have manual rolling enabled, but the automatically rolled attack does not show 3d dice.

**Comment by MangoFVTT** [comment] 2024-08-05 13:48
Just noting that I am looking into this, but the DSN update has some fairly major changes to the API functions that will take time to fix with RSR

**Comment by MangoFVTT** [comment] 2024-08-06 09:09
After investigating, the issue appears to be caused by a bug in DSN. I've reported it to the author here: https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues/435

**Comment by nschoenwald** [comment] 2024-08-26 16:53
No fix has been published for this in Dice So Nice yet. The last version (5.0.5) was published over three weeks ago. So we will have to wait for the next release for this to be fixed. I'm still using the last v4 release in the meantime.

**Comment by MangoFVTT** [comment] 2024-10-21 17:21
As of DSN 5.1.3 and RSR 3.3.0, this no longer seems to be an issue. DSN is rolling largely as expected for me. I would advise creating new tickets for any DSN related issues that come up moving forward.

**Closed by MangoFVTT** 2024-10-21 17:21 UTC
Labels: bug
