### ISSUE TITLE
[BUG] Quick Roll not consuming item charges

### ISSUE THREAD

**Issue by ZayviNZL** [MangoFVTT/fvtt-ready-set-roll-5e#35] opened 2022-09-11 06:52 UTC
With quick roll enabled for items, when using an item with charges, the charges are not being consumed on the item.

**Comment by MangoFVTT** [comment] 2022-09-11 08:27
@ZayviNZL Have you ensured that the Uses consumable is checked inside the roll configuration for the item? Some items default to not using charges when you first add them (e.g. weapons), so you should enable the Uses check to make sure that happens. From my testing, enabling this checkbox seems to work as intended with consuming uses/charges.

![image](https://user-images.githubusercontent.com/110994627/189518512-cc19a3ca-2974-4ffe-a5ae-bf2509a5fb85.png)

**Comment by ZayviNZL** [comment] 2022-09-11 10:06
I have since reverted back to V9 as I ran into errors with other modules so I can't check, but I'm sure I didn't even know that tab existed on the items so I wouldn't have even checked there. No doubt that would have solved the problem.
I'll upgrade to V10 again after my next session and confirm if it was user error or not

**Comment by MangoFVTT** [comment] 2022-09-11 10:17
No worries! Not everyone uses the roll configuration so it's an understandable mistake. Let me know if this was in fact the problem so I can close this issue ticket 👍

**Closed** 2022-09-13 09:32 UTC
Labels: bug
