### ISSUE TITLE
[BUG] Disabling attack roll in quick rolls causes default item card to be rolled

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#361] opened 2024-02-17 11:58 UTC
**Description**
If an item with an attack roll has its attack roll disabled, it will roll the default foundry item card with non of the RSR additions/improvements
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/8a938bfc-00dd-458f-a343-1d20099de89f)

**Steps to Reproduce**
1. Have an item that has an attack roll (and possibly a damage roll?)
2. Go to quick roll and disable the attack roll option
3. Roll the item
4. See result
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/d290505c-0640-46e6-b5ff-9424983b36bc)
(also works if i swap the normal and alt rolls settings around btw)

**Versions**
 - Module: [3.0.7]
 - dnd5e: [3.0.2]
 - Foundry: [11.315]

**Other Modules**
A list of any other installed modules that might be related to the issue.
-None

**Comment by maxobremer** [comment] 2024-02-17 12:05
also to not make a new issue for a single question, is it feasible to have the damage types split like it was in the pre dnd5e v3 version of this module? would be nice for situations like ice knife and the Giant Spider's Bite as those have some conditional damage

**Comment by MangoFVTT** [comment] 2024-02-17 12:32
@maxobremer I haven't been able to reproduce this issue on my end. Disabling the Attack in the quick roll config seems to work as expected for multiple items (see image below). Could you check if this problem is happening for you on all items? If not, try recreating the item that is giving you the problem.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/0adab702-4053-4db8-ac11-860edf79d2b8)

> also to not make a new issue for a single question, is it feasible to have the damage types split like it was in the pre dnd5e v3 version of this module? would be nice for situations like ice knife and the Giant Spider's Bite as those have some conditional damage

Damage types are split inside the tooltip now, since RSR uses the default dnd5e system damage output to split up damages appropriately. You can access the individual damage types by opening the tooltip:

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/6d54faaa-616b-4dba-b216-7a1aabdc1733)

**Comment by maxobremer** [comment] 2024-02-17 14:07
Made a new actor and a new weapon and got the same result:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/32487c11-de0b-4ad1-bfaa-c8fe00faa016)

Just in case, here is a list of my settings:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/068174b7-18e2-41d4-9768-c2f7082d7ba3)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/3a85202c-09db-4b8f-b15f-8fd56bd48ebe)

after messing around a bit I think it has to do with the Always Roll Multiple Dice settings. With that unchecked the issue doesn't seem to be there but with it checked it is.


> Damage types are split inside the tooltip now, since RSR uses the default dnd5e system damage output to split up damages appropriately. You can access the individual damage types by opening the tooltip:

Maybe I should rephrase, is it feasible to have them be separate buttons to roll and show up split outside the tooltip? Else you have most situations where the players need to apply just the total sum, but only a few where they have to open up the tooltip to then apply the individual damages. Also the damages in the tooltip still gets bundled together if they have the same type, even when they might be meant for different things. For example a Giant Slayer Longsword (and to note the other formula field doesn't really work well since you can apply context or a damage type to that properly)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/e5df7b7c-d6f5-4f3e-8d7f-3c2556517023)


Or whatever else:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/49a9f70d-3f2e-4cb4-b7da-9b292cd792a4)

**Comment by MangoFVTT** [comment] 2024-02-17 16:10
Your primary bug has been resolved and will be in the next release.

> Maybe I should rephrase, is it feasible to have them be separate buttons to roll and show up split outside the tooltip? Else you have most situations where the players need to apply just the total sum, but only a few where they have to open up the tooltip to then apply the individual damages. 

No unfortunately not that feasible. Since RSR 3.0 is more closely tied to system behaviour now (to facilitate maintenance and make it work better with other popular modules) it relies on how the system rolls damage, and the system does that as a whole package. You CAN use alternate rolls to have two separate batches of damage, but that's the extent of the functionality RSR offers. That being said, compatibility with Roll Groups (which does exactly what you are asking for) is being worked on and can be tracked in #331.

> Also the damages in the tooltip still gets bundled together if they have the same type, even when they might be meant for different things. 

This is a dnd5e system issue (it bundles same damage types together internally, nothing RSR can do about it), and should be brought up on their github. It bothers me as well, and I wouldn't be surprised if there were already issues requesting it be changed.

**Closed by MangoFVTT** 2024-02-17 16:10 UTC
Labels: bug
