### ISSUE TITLE
[BUG] Module incompatibility

### ISSUE THREAD

**Issue by MushroomRain** [MangoFVTT/fvtt-ready-set-roll-5e#404] opened 2024-03-08 23:33 UTC
RSR with combination of two modules disables ATTACK message in chat (you cant see what u rolled)

**Steps to Reproduce**
1. Install Ready set roll ver. 3.0.13
2. Instal Dice So Nice! ver. 4.6.10
3. Instal Simple Calendar ver. 2.4.8
4. Activate ALL three modules
5. Roll attack from character list

If one module (Dice or Calendar) activated with RSR - message in chat doesnt disapear

**Versions**
 - Module: [3.0.13]
 - dnd5e: [3.0.0-3.0.4]
 - Foundry: [11.315]

**Other Modules**
Dice So Nice! ver. 4.6.10
Simple Calendar ver. 2.4.8

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/162760577/cf30e839-8eaf-403c-afe0-d78fb87fb8c2)

**Comment by Juneybugged** [comment] 2024-03-10 17:23
Can confirm, having the exact same issue, with the exact same reproducible steps.

**Comment by dczwardCZAR** [comment] 2024-03-10 18:43
Can confirm, exact same issue, same reproducible steps. "Find the Culprit" shows there's a conflict with Simple Calendar.

**Comment by SilentDM** [comment] 2024-03-11 23:47
I just tested it and Disabling Simple Calendar does fix the issue.

**Comment by thepting** [comment] 2024-03-12 06:16
Came here to check to see if Dice So Nice incompatibility had been reported, and found a great workaround.  You are all geniuses, thank you for  figuring out that I can disable Simple Calendar and make it work while keeping Dice So nice for tomorrow's game.

**Comment by crash1115** [comment] 2024-03-15 16:59
Another workaround for the folks who rely on SC for their games - enable the "Display chat message immediately" setting in DSN. This lets the rolls show as normal with both DSN and SC active. Obviously it also removes the delay, potentially spoiling important rolls, but that's maybe less bad than alternatives.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/41387713/0116a992-82ee-4867-8bfe-81d5e856ffb2)

**Comment by DF1225** [comment] 2024-03-22 03:21
Enabling "Display chat message immediately" on DSN is fixing the issue for me but now damage isn't rolling automatically - only manually despite me changing it in RSR settings.

**Comment by MangoFVTT** [comment] 2024-03-22 08:49
@DF1225 that's likely because you have updated to 3.1, see the bug ticket #411.

**Comment by MangoFVTT** [comment] 2024-03-22 08:54
@MushroomRain @Juneybugged @dczwardCZAR @SilentDM I'm currently testing this issue with the following module versions and seem unable to reproduce the issue:
- Dnd5e [3.1.0]
- RSR [3.0.13]
- Dice So Nice [4.6.10]
- Simple Calendar [2.4.13]

Can any of you confirm if the problem is still coming up for you with all modules and system updated to latest?

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/a0876cd2-f528-44d2-839f-3dcb3a3a8bbc)

**Comment by MushroomRain** [comment] 2024-03-22 13:19
> * Dnd5e [3.1.0]
> * RSR [3.0.13]
> * Dice So Nice [4.6.10]
> * Simple Calendar [2.4.13]

With this versions can confirm there is no issue anymore

**Comment by MangoFVTT** [comment] 2024-03-22 23:02
Fantastic, closing this ticket as resolved for now. A new ticket can be opened if issues arise moving forward

**Closed by MangoFVTT** 2024-03-22 23:02 UTC
Labels: bug
