### ISSUE TITLE
[BUG] Rolling an item causes a TypeError exception

### ISSUE THREAD

**Issue by erizocosmico** [MangoFVTT/fvtt-ready-set-roll-5e#265] opened 2023-11-18 15:42 UTC
**Description**
Item `hasResource` is now a getter-only property. In `ensurePropertiesOnItem` (`src/utils/item.js`) on line 215 it's attempting to set a value in that property, which causes an exception to be thrown when trying to roll an item. I tried commenting this line and it works as expected. Didn't submit a patch for it, because I'm not that familiar with the 5e item and this module internals and just removing the line might probably have unintended consequences.

**Steps to Reproduce**
1. Go to Inventory
2. Roll any item that's not a spell

**Versions**
 - Module: 2.1.3
 - dnd5e: 2.4.0
 - Foundry: 11.315

**Other Modules**
n/a

**Comment by MangoFVTT** [comment] 2023-11-18 17:15
@erizocosmico this issue has been resolved already but not yet released. It is caused by dnd 5e 2.4.0. Temporary fix is to downgrade dnd versions until RSR is updated.

Duplicate of #263.

**Closed by MangoFVTT** 2023-11-18 17:15 UTC
Labels: bug
