### ISSUE TITLE
Weapon Critical Hit Threshold ignored when (Enable Quick Roll for Items) is ON

### ISSUE THREAD

**Issue by Weskernation** [MangoFVTT/fvtt-ready-set-roll-5e#120] opened 2022-12-04 22:10 UTC
**Description**
Crit roll threshold is being ignored when "Enable Quick Roll for Items" is ON.
When a character crits at 19 (e.g. Fighter Champion - Improved Critical) when the quick roll option is turned on it will only crit at 20 instead of 19.
When the option is turned OFF, after a roll you have to click "Attack" in the chat and then Advantage/Normal/Disadvantage on the popup (I find that annoying during gameplay). You will see It will crit at 19 as it should

**Steps to Reproduce**
In the settings turn ON the "Enable Quick Roll for Items"
1. Go to a character sheet Attributes tab
2. Scroll down to Special Traits
3. Under Feats change the number at "Weapon Critical Hit Threshold" to 5 (for easy example) Scroll down and "Update Special Traits"
4. Click on Inventory and click the icon of a weapon to make an Attack. 
5. See error that your roll will not crit when it is 5 or over unless it is the standard 20
6. Now In the settings turn OFF the "Enable Quick Roll for Items"
7. Click on Inventory and click the icon of a weapon to make an Attack. In the chat click Attack then select advantage/normal/disadvantage
8. See you will crit on 5 and up
9. **Same goes for Spell Critical Threshold**

The issue is the same when instead of step 3 the threshold is changed on the item(weapon) or adding an effect (flags.dnd5e.weaponCriticalThreshold) on the character sheet

**Versions**
 - Module: [1.3.13]
 - dnd5e: [2.0.3]
 - Foundry: [10.291]

**Comment by MangoFVTT** [comment] 2023-01-10 09:23
@Weskernation I am unable to reproduce this bug on my end. Changing the global weapon critical hit threshold behaves as expected when making weapon attacks (see image 1) and the same goes for changing the individual weapon critical hit threshold (see image 2). 

![image](https://user-images.githubusercontent.com/110994627/211511421-f7193867-b254-44e3-99ae-755678b30ec6.png)
![image](https://user-images.githubusercontent.com/110994627/211511773-6bdbc096-e462-464c-b236-903c4b9c0a6c.png)

Can you ensure that you are not running any other modules that would interfere with rolls (e.g. midi QOL) or any modules that mess with the traits? Also attempt to reproduce the issue on multiple weapons/spells

**Comment by Weskernation** [comment] 2023-01-10 23:46
@MangoFVTT I am cluesless, thank you for your reply/time

I have MidiQOL but it is disabled.
With Find culprit, it show it is from RSR. 
Even when every other module is turned off (only 3 active) I cannot get it to work.

<img width="1814" alt="image" src="https://user-images.githubusercontent.com/119079571/211685265-daaa4071-2e69-4400-be51-c914c04f2aa7.png">

**Comment by Weskernation** [comment] 2023-01-10 23:55
@MangoFVTT I saw there is an update today, and now everything works fine. with all the modules activated in my original post

**Comment by MangoFVTT** [comment] 2023-01-11 08:35
@Weskernation Interesting, I did change some minor things related to critical thresholds, but nothing that should have affected this. Either way, if it's fixed I will close this ticket for now. If it re-occurs, please let me know via a new issue ticket 🙂

**Closed by MangoFVTT** 2023-01-11 08:35 UTC
Labels: bug
