### ISSUE TITLE
[FEATURE] Restoring the old split damage display in chat cards.

### ISSUE THREAD

**Issue by Aleswall** [MangoFVTT/fvtt-ready-set-roll-5e#392] opened 2024-03-03 16:06 UTC
**Is your feature request related to a problem? Please describe.**
In prior versions of Ready Set Roll, if you had two different damage formulae on a weapon or a spell with different damage types and context text set for them, they would display individually on chat cards.

**Describe the solution you'd like**
I'd like at least an option to return to this, it's the main reason I use this module in particular as it makes spells or weapons that have multiple damage types much easier to manage in the case that a creature resists one type of damage but not the other. Being able to individually apply full damage on one and half damage on the other due to there being two sets of buttons saved me a lot of time.

**Additional context**
I accept that others may not like this as it does bloat the chat-card, which is why I think that it should be optional if it's restored at all.

**Comment by MangoFVTT** [comment] 2024-03-03 16:19
Duplicate of #392.

> this is a dnd5e issue not an RSR issue. For some reason it was decided to collect all damage of the same type into one group by the damage function, and since RSR now relies purely on system calculations to display things (for maintenance and compatibility reasons), it therefore displays that damage as the same group. I recommend making an issue for this on the dnd5e github and complaining that damage shouldn't be randomly collected into a single group if specifically made separate in the item card (I agree by the way).

**Closed by MangoFVTT** 2024-03-03 16:19 UTC

**Comment by MangoFVTT** [comment] 2024-03-03 16:38
@Aleswall note that damage of different types still shows up separately, you need to expand the tooltip:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/d87e8402-839d-4cfb-a012-04d95535878c)

**Comment by Aleswall** [comment] 2024-03-03 16:48
Okay, thank you, sorry - I realise my mistake! I had checked and seen that you could expand the damage to see the individual rolls and types, but the buttons were not there on the individual damage types. I realise now I had no token selected, the big damage buttons at the bottom being there convinced me I was (relating to #389), I guess.

Sorry for the bother again, absolutely my own oversight.
