### ISSUE TITLE
[BUG] The given roll is null or undefined. - Incompatibility with Module "Die Hard"

### ISSUE THREAD

**Issue by Shareenx** [MangoFVTT/fvtt-ready-set-roll-5e#118] opened 2022-12-01 21:15 UTC
**Description**
The module was working fine, 
I added a new weapon and made some edits to another and now ANY character sheet, any weapon or spell throws this error.
"The given roll is null or undefined."

**I did all the things below, then used "Find the Culprit"**
The issue is some incompatibility with "Die Hard" that weirdly, only occurred several minutes into me creating and testing weapons.
I left all the text from the troubleshooting, in case it is of interest.
Next time I have an issue with a module, I think I'll start with "Find the Culprit"

**Steps to Reproduce**
Things I did right before everything broke
1. Modify a melee weapon to use Strength, when Str was below 10 (negative modifier)
2. Deleted some extra damage lines (left the original)
3. Added a new weapon

![Capture](https://user-images.githubusercontent.com/81126418/205160437-9caff85d-b51d-43a6-bab6-83bdcba4ee0e.PNG)

Now
1. Go to any character sheet
2. Click to use any spell or weapon
3.  See error

Tried 
Did not work:
- making a new weapon
- reloading (browser refresh)
- unchecking the option to auto roll damage the item, per damage line

Stopped the error
- returned to set-up (to make sure I had the latest versions of everything)
- I can't get it to repro

**Versions**
- RSR Version: 1.3.13
- System: D&D 5E v 2.03
- Foundry: 10.290

**Other Modules**
Die Hard

Console:
Ready Set Roll | Quick rolling Item 'New Weapon'.
log.js:21 Ready Set Roll | The given roll is null or undefined.
logError @ log.js:21
ensureMultiRoll @ roll.js:260
_addFieldAttack @ item.js:402
await in _addFieldAttack (async)
getFieldsFromItem @ item.js:62
await in getFieldsFromItem (async)
_getItemRoll @ roll.js:408
rollItem @ roll.js:189
(anonymous) @ hooks.js:91
#call @ foundry.js:724
callAll @ foundry.js:681
use @ dnd5e.mjs:6981
await in use (async)
🎁call_wrapped @ lib-wrapper.js:1
rollItemWrapper @ roll.js:102
_itemProcessWrapper @ patching.js:149
_itemUse @ patching.js:111
🎁CONFIG.Item.documentClass.prototype.use#0 @ lib-wrapper.js:1
_onItemUse @ dnd5e.mjs:12504
(anonymous) @ dnd5e.mjs:12165
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
render.js:170 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'terms')
[Detected 1 package: ready-set-roll-5e]
    at _renderMultiRoll (render.js:170:29)
    at _renderAttackRoll (render.js:230:12)
    at RenderUtility.renderFromField (render.js:54:24)
    at QuickRoll._render (quickroll.js:322:52)
    at async QuickRoll.toMessage (quickroll.js:169:13)
    at async _getItemRoll (roll.js:429:5)
    at async RollUtility.rollItem (roll.js:189:16)
_renderMultiRoll @ render.js:170
_renderAttackRoll @ render.js:230
renderFromField @ render.js:54
_render @ quickroll.js:322
await in _render (async)
(anonymous) @ hooks.js:91
#call @ foundry.js:724
callAll @ foundry.js:681
use @ dnd5e.mjs:6981
await in use (async)
🎁call_wrapped @ lib-wrapper.js:1
rollItemWrapper @ roll.js:102
_itemProcessWrapper @ patching.js:149
_itemUse @ patching.js:111
🎁CONFIG.Item.documentClass.prototype.use#0 @ lib-wrapper.js:1
_onItemUse @ dnd5e.mjs:12504
(anonymous) @ dnd5e.mjs:12165
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by MangoFVTT** [comment] 2023-01-08 17:03
This is a duplicate of #32. Progress on module compatibility for Die Hard can be tracked there.

**Closed by MangoFVTT** 2023-01-08 17:03 UTC
Labels: bug
