### ISSUE TITLE
[BUG] more than 2 d20 roll when rolling for attack in v12

### ISSUE THREAD

**Issue by Rommel-holmes** [MangoFVTT/fvtt-ready-set-roll-5e#447] opened 2024-06-17 17:38 UTC
**Description**

When rolling attack in foundry v12, 3 (or 5) d20 will roll instead of 2.

** Reproduce**

Just roll an attack in the character sheet by clicking dagger/hammer, for example.

**Version**
1. Foundry v12
2. DND 5e 3. 2
3. Dice so nice 4.6.10
4. Ready set roll 3.1.0
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/3947498/282c1c0c-1686-4e1e-92e9-f0e7a8cc1b2a)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/3947498/484f3910-1187-4357-bcc4-6ff423c91863)

**Comment by MangoFVTT** [comment] 2024-07-24 09:50
Closing this as a duplicate of #450

**Closed by MangoFVTT** 2024-07-24 09:50 UTC
Labels: bug
