### ISSUE TITLE
[FEATURE] Show damage buttons on damage rolls created by enrichers

### ISSUE THREAD

**Issue by crash1115** [MangoFVTT/fvtt-ready-set-roll-5e#393] opened 2024-03-03 16:08 UTC
**Is your feature request related to a problem? Please describe.**
You can use enrichers to generate damage rolls by doing something like this: `[[/damage 2d6 type=fire]]`. Clicking on them will generate a chat card similar to the ones vanilla 5e uses when you deal damage with a weapon. Presently, RSR's damage application buttons do not appear on these cards.

**Describe the solution you'd like**
If it's possible, having those buttons rendered in the enricher-generated damage cards would be wonderful.

**Describe alternatives you've considered**
N/A

**Additional context**
There's a pretty strong use case for using enrichers in the description field of weapons to let players apply damage that only applies conditionally (_especially_ while dnd5e combines all the damage rolls of similar types into one field on the card, which I know is not a super popular decision around here).

As an example, my paladin has a weapon that deals additional radiant damage to casters, but also has Improved Divine Smite. We put the bonus caster damage in the description via enricher, since it only applies sometimes, and put the IDS damage into the weapon's damage since that's always on. Not being able to leverage RSR's damage application features with the bonus damage cards is mildly inconvenient.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/41387713/235b0713-0d27-4ae7-b755-716d776344f0)

**Comment by MangoFVTT** [comment] 2024-03-03 16:18
Duplicate of #303.

**Closed by MangoFVTT** 2024-03-03 16:18 UTC
