### ISSUE TITLE
[BUG] Damage Context not Showing

### ISSUE THREAD

**Issue by maoyuans** [MangoFVTT/fvtt-ready-set-roll-5e#434] opened 2024-05-29 03:40 UTC
**Description**
Damage context does not show up when expanding the damage roll. There is also no module setting relating to context. The relevant sections in readme.md seem to still suggest that it is a feature.

**Steps to Reproduce**
1. Make item or skill with any damage component.
2. Put context on damage formula.
3. Roll item or skill.
4. Expand damage roll.
5. No context?

**Versions**
 - Module: [3.0.14]
 - dnd5e: [3.2.0]
 - Foundry: [11.315]

**Other Modules**
None. Behavior persists with only RSR enabled.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/33184314/e54172ed-9ec6-4637-9711-0d25e25da9a7)

**Comment by MangoFVTT** [comment] 2024-06-11 07:10
@maoyuans I cannot reproduce this on the versions you have mentioned. Context seems to show correctly for me: 
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/6397b1f3-4241-4bea-88e4-340cd23997c4)

Please confirm if you are actually still on v11 or have updated to v12. Otherwise, I would recommend recreating the item and seeing if that fixes anything.

**Comment by MangoFVTT** [comment] 2024-06-11 07:33
On further investigation this seems possibly related to manual damage rolling. Are you currently using an RSR option where damage is rolled manually via a button click on the chat card?

**Comment by MangoFVTT** [comment] 2024-06-11 07:38
This issue is likely fixed and will be in the next release.

**Closed by MangoFVTT** 2024-06-11 07:38 UTC
Labels: bug
