### ISSUE TITLE
[FEATURE] Off option for Quick Roll Image Used

### ISSUE THREAD

**Issue by XardisSevenfold** [MangoFVTT/fvtt-ready-set-roll-5e#108] opened 2022-11-11 22:36 UTC
I use Chat Portrait to signal who rolled what, and it comes with the option to also have icons for ability and skill rolls. But those rolls are overriden with the actor or token icon by this module.

Before this, Ive used Better Rolls 5e for v9 of Foundry and there was no such issue. It might be that Foundry loads modules in an alphabetical order and before  Chat Portraits overrode the icons from this module, but now the reverse is happening, and I cannot find anything that manipulate the load order of modules.

**Comment by MangoFVTT** [comment] 2022-11-16 21:48
Load order should not matter, but unfortunately support for modules that both interact with rolls/chat cards is notoriously finnicky and difficult to work around. I can try to take a look into the situation, but I can't promise fast results.

**Comment by MangoFVTT** [comment] 2023-01-10 09:24
This seems to be a duplicate of #121 and should be fixed in the next update.

**Closed by MangoFVTT** 2023-01-10 09:24 UTC
Labels: enhancement
