### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ArcangeloD** [MangoFVTT/fvtt-ready-set-roll-5e#2] opened 2022-09-06 16:32 UTC
Hello,

I actually cannot install the module for now, here's the error in the console  : 

[ready-set-roll-5e] Metadata validation failed for module "ready-set-roll-5e": The file "lib/libwrapper/shim.js" included by module ready-set-roll-5e does not exist

**Comment by MangoFVTT** [comment] 2022-09-06 16:54
Closing this as a duplicate of [#3](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/3)

**Closed** 2022-09-06 16:56 UTC
Labels: bug, duplicate
