### ISSUE TITLE
Bugged Interaction with chat portrait modules

### ISSUE THREAD

**Issue by poozi** [MangoFVTT/fvtt-ready-set-roll-5e#121] opened 2022-12-06 05:53 UTC
**Description**
Whenever a quick roll is used, the attack roll shows up normally, however if "always roll manual damage" is selected, when the damage is rolled, the number does not replace the "damage button" on the chat card if a module such as "Simply Portraits" or "Chat Portraits is used. The bug occurs only if the token of the character sheet you're rolling from is placed on the currently active scene. It does not occur if the current scene does not have a token belonging to the character the attack is rolled from. 

**Steps to Reproduce**
1. Have "Always roll damage manually" checked in settings
2. Place character token on currently active scene
3. Open the character sheet and use anything with a weapon attack.
4. If a chat portrait module is active, the damage dice is rolled but the number does not replace the damage button on the chat card
5. See error

**Versions**
 - Module: [1.3.13]
 - dnd5e: [2.0.3]
 - Foundry: [10.291]

**Other Modules**
Simply Portraits, Chat Portraits

**Comment by XardisSevenfold** [comment] 2022-12-12 19:24
I can confirm the same happening to me. Ive also tested it out with Ready Set Roll + one Simple Portraits but I didnt manage to replicate it, only happens with Chat Portraits for me.

**Comment by Kerdude** [comment] 2022-12-14 22:31
Confirming I am seeing this as well - no matter if the actor or token image is selected in RSR settings

**Comment by Kerdude** [comment] 2022-12-14 22:33
Uncaught (in promise) Error: All provided terms must be RollTerm instances
[Detected 2 packages: ready-set-roll-5e, lib-wrapper]
    fromTerms foundry.js:10101
    _renderMultiRoll render.js:171
    _renderAttackRoll render.js:230
    renderFromField render.js:54
    _render quickroll.js:322
    toMessageUpdate quickroll.js:201
    _updateQuickCard quickcard.js:312
    _processDamageButtonEvent quickcard.js:177
    _setupActionButtons quickcard.js:94
    jQuery 9
    _setupActionButtons quickcard.js:93
    updateBinding quickcard.js:38
    QuickCard quickcard.js:20
    bindChatCard chat.js:30
    registerChatHooks hooks.js:101
    #call foundry.js:724
    call foundry.js:706
    getHTML foundry.js:18165
    _renderBatch foundry.js:74141
    _renderInner foundry.js:74110
    _render foundry.js:5114
    _render foundry.js:60343
    _render foundry.js:74100
    _render foundry.js:60113
    render foundry.js:5067
    initializeUI foundry.js:8069
    setupGame foundry.js:7931
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675
foundry.js:10101:13

**Comment by Albolynx** [comment] 2022-12-17 16:46
Adding more information:

Tested and indeed this happens with ChatPortraits module - for me the main issue is that retroactive Advantage/Disadvantage does not work. Same error as the above comment.

I also noticed that it only happens if there is a token on the scene for the Actor from which the roll happens. So if I have an Actor I pick from the sidebar, it rolls fine and Adv/Disadv can be retroactively rolled. But if that Actor is on the scene, whether I select it from the sidebar or doubleclick (and whether data is linked or not), this error goes off and Adv/Disadv does not work.

**Comment by thejoester** [comment] 2022-12-19 07:30
I am having the same problem as @Albolynx. I tested again and can replicate the same behavior. If the token is on the scene when the action is rolled then the Advantage/Disadvantage function does not apply and there is an error in the console, pasted below with my IP censored. 

```
00:27:02.444 Uncaught (in promise) Error: All provided terms must be RollTerm instances
[Detected 1 package: ready-set-roll-5e]
    fromTerms http://##MYSERVERIP##:30000/scripts/foundry.js:10101
    _renderMultiRoll http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/utils/render.js:171
    _renderAttackRoll http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/utils/render.js:230
    renderFromField http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/utils/render.js:54
    _render http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickroll.js:322
    toMessageUpdate http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickroll.js:201
    _updateQuickCard http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickcard.js:312
    _processRetroButtonEvent http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickcard.js:198
    _setupMultiRollOverlayButtons http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickcard.js:130
    jQuery 9
    _setupMultiRollOverlayButtons http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickcard.js:129
    _setupOverlayButtons http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickcard.js:104
    updateBinding http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickcard.js:48
    jQuery 11
    updateBinding http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickcard.js:45
    QuickCard http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickcard.js:20
    bindChatCard http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/utils/chat.js:30
    registerChatHooks http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/utils/hooks.js:101
    #call http://##MYSERVERIP##:30000/scripts/foundry.js:724
    call http://##MYSERVERIP##:30000/scripts/foundry.js:706
    getHTML http://##MYSERVERIP##:30000/scripts/foundry.js:18165
    postOne http://##MYSERVERIP##:30000/scripts/foundry.js:74257
    _onCreate http://##MYSERVERIP##:30000/scripts/foundry.js:18242
    callback http://##MYSERVERIP##:30000/scripts/foundry.js:12612
    documents http://##MYSERVERIP##:30000/scripts/foundry.js:12562
    _handleCreateDocuments http://##MYSERVERIP##:30000/scripts/foundry.js:12562
    _createDocuments http://##MYSERVERIP##:30000/scripts/foundry.js:12468
    create http://##MYSERVERIP##:30000/scripts/commons.js:6738
    createDocuments http://##MYSERVERIP##:30000/scripts/commons.js:6110
    create http://##MYSERVERIP##:30000/scripts/commons.js:6233
    toMessage http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/module/quickroll.js:182
    _getItemRoll http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/utils/roll.js:429
    rollItem http://##MYSERVERIP##:30000/modules/ready-set-roll-5e/src/utils/roll.js:189
foundry.js:10101:13

```

**Comment by nschoenwald** [comment] 2022-12-20 15:22
I am having the same issue.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/72390280/208702305-32fa877b-8f5d-464c-9aac-e302f352fc45.png">

**Comment by cs96and** [comment] 2022-12-22 11:46
Also seeing this.  If either Chat Portraits or Simply Portraits is enabled.

**Comment by ConnorSolo** [comment] 2022-12-30 06:23
Just wanted to add that I'm encountering the same issue of the retroactive advantage/disadvantage roll not appearing on the chat card. Instead it throws this error in the console.

![Screenshot 2022-12-29 221137](https://user-images.githubusercontent.com/40305990/210040798-44b16e03-3533-460e-a349-01504a5b6dbc.png)

I disabled the Chat Portraits module and this functionality was restored. However, I did still notice this error (see below) in the console when I clicked on the +/- sign to add the advantage/disadvantage roll. I'm not sure what it means, but hopefully it might help you figure out what the issue might be.

![Screenshot 2022-12-29 222022](https://user-images.githubusercontent.com/40305990/210040707-f2b95e3d-8e4b-4afc-be02-714f1fe9f19b.png)

Thanks!

**Comment by thejoester** [comment] 2022-12-31 05:53
Since it has been a month and no response or acknowledgement, I thought I would share this workaround that I found that allows me to keep chat portraits (as the DM it is VERY helpful how it colors the chats so I can look for actions from a specific player). 

In Ready Set Roll you need to [enable "Always Roll Multiple Dice"](https://i.imgur.com/2FdlpkC.png). This will always roll two dice (three with Elven Accuracy) and for normal rolls just always use the first (left) number.

**Comment by cs96and** [comment] 2023-01-04 17:42
I've been looking into this problem, and it is related to how RSR stores data in the flags of `ChatMessage` objects.

`flags.rsr5e.fields` is an array, and within that there can be `D20Roll` class objects.  These `D20Roll` objects contain a `terms` array which contain various class objects such as `Die`, `OperatorTerm` etc.

Simply Portraits calls `updateSource` in the "preCreateChatMessage" hook.  `updateSource` converts all the class objects into bare JS objects.  These bare objects are what end up getting written to the database.  When `QuickRoll.fromMessage()` is called, you get  the bare objects back again instead of the classes, and then eventually `Roll.fromTerms()` fails, because it expects classes, not bare objects.

I had a conversation about this on the discord server.  Supposedly, storing classes in flags is not supported, and only bare objects should be used instead.  So storing `D20Roll` objects in the flags is a no-go, and should be changed.

https://discord.com/channels/170995199584108546/811676497965613117/1060243153187242164

**Comment by cs96and** [comment] 2023-01-05 12:09
I've submitted a PR to fix the issue.  Hopefully it will get picked up.

**Comment by MangoFVTT** [comment] 2023-01-08 16:53
Good catch and good work on the fix. I've merged the PR and will have the fix in the next release

**Closed by MangoFVTT** 2023-01-08 16:53 UTC
Labels: bug

**Comment by cs96and** [comment] 2023-01-09 11:23
Any idea when this will be released?

**Comment by MangoFVTT** [comment] 2023-01-10 10:21
> Any idea when this will be released?

@cs96and Version 1.3.14 was released this morning and should include this fix
