### ISSUE TITLE
[BUG] Skill Checks are not triggering Dice So Nice and/or dice sound

### ISSUE THREAD

**Issue by rtakehara** [MangoFVTT/fvtt-ready-set-roll-5e#18] opened 2022-09-07 00:06 UTC
**Description**
The module doen't appear to be triggering Dice So Nice when rolling Skill Checks, Saving Throws and Attack Rolls, Damages and other rolls work fine.

I also tried using just RSR with no other modules, and dice rolls don't reproduce any sound.

**Steps to Reproduce**
1. Roll any skill check

**Versions**
 - Module: [1.0.2]
 - dnd5e: [2.0.2]
 - Foundry: [10.284]

**Other Modules**
Dice So Nice, but I also tried with nothing and there is no dice roll sound.

**Comment by KumoGekkou** [comment] 2022-09-07 05:20
More specifically, with Dice so Nice, it does not roll any d20s. Since skill checks are only d20's it's most obvious, but when using attack's, only the damage dice are rolled through Dice so Nice, not the d20s.

**Comment by MangoFVTT** [comment] 2022-09-07 06:14
Support for other modules is not yet something I've spent much time on. I will be focusing on getting the module itself to a stable state and hopefully achieving feature parity with Better Rolls first, before moving on to fixing compatibility issues. If I had to guess, it's likely because Dice so Nice and this module both hook into dice rolling functions and might be interfering with each other.

Dice Sounds are on the docket and will be worked on in a future release

**Comment by KumoGekkou** [comment] 2022-09-07 13:56
> Support for other modules is not yet something I've spent much time on. I will be focusing on getting the module itself to a stable state and hopefully achieving feature parity with Better Rolls first, before moving on to fixing compatibility issues. If I had to guess, it's likely because Dice so Nice and this module both hook into dice rolling functions and might be interfering with each other.
> 
> Dice Sounds are on the docket and will be worked on in a future release

Yes, thank you. I should have started with thanking you for building this at all. I was devastated to learn better rolls was abandoned and truly appreciate your work!

**Comment by MangoFVTT** [comment] 2022-09-07 14:02
You're very welcome! Just so you know, Dice roll sounds are being added in the 1.1.0 release, which shouldn't be too far out.

**Comment by MangoFVTT** [comment] 2022-09-07 18:52
Closing this as Dice Sounds are now released. Dice So Nice functionality will happen at a later date.

**Closed** 2022-09-07 18:51 UTC
Labels: bug

**Comment by KumoGekkou** [comment] 2022-09-07 18:53
Just a note, the Dice so Nice is working, just not D20 rolls. All other rolls that use both are working as intended.

**Comment by MangoFVTT** [comment] 2022-09-08 16:45
@KumoGekkou @rtakehara Dice So Nice compatibility is now fixed with Release 1.2.0 and D20 rolls should roll 3D dice correctly.
