### ISSUE TITLE
[BUG] Compatibility with Roll Groups Issue

### ISSUE THREAD

**Issue by DrWiFi** [MangoFVTT/fvtt-ready-set-roll-5e#385] opened 2024-02-25 23:08 UTC
**Description**
With Ready Set Roll and Roll Groups enabled, rolling damage from the Roll Group interface generates errors.
Issue only happens when both Roll Groups and Ready Set Roll are installed.
<img width="1085" alt="Screenshot 2024-02-25 at 2 43 30 PM" src="https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/50341031/dc5465b7-c207-48e9-9161-fdf176519cba">

**Steps to Reproduce**
1. Configure Cantrip and Weapon with Roll Groups
2. Cast Cantrip
3. Click either Weapon Attack or Combined Damage
4. Roll Damage
5. Dice will roll, but no chat output, plus error in console
<img width="1085" alt="Screenshot 2024-02-25 at 3 06 30 PM" src="https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/50341031/50b265f8-dd99-4c8d-ba32-04e6bcd67987">

**Versions**
 - Module: [3.0.10]
 - dnd5e: [3.0.3]
 - Foundry: [11.315]

**Other Modules**
Roll Groups

Thanks

**Comment by MangoFVTT** [comment] 2024-02-26 08:46
@DrWiFi Compatibility for Roll Groups is already being tracked in this ticket: #331.

However as per my current tests, while Roll Groups and RSR does lead to some strange behaviour for cards, I see no errors coming up as you are experiencing. An item with Roll Groups set up will correctly display damage buttons for those roll groups, and roll them into separate cards as expected. 

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/e77ab951-64f1-4f55-94a6-15f6181467a8)

Are you certain you are not using any other modules? The popup window I see in your screenshot as far as I know does not come from Roll Groups and does not come from RSR either, for example.

**Comment by DrWiFi** [comment] 2024-02-27 16:47
Yes, Zhell is correct.
The Cantrip I setup for this was Booming Blade as a blade cantrip.
Sorry for that missing information.

**Comment by MangoFVTT** [comment] 2024-03-03 16:23
In that case, I'm closing this as a duplicate of #331 and use that ticket for tracking.

**Closed by MangoFVTT** 2024-03-03 16:23 UTC
Labels: bug, duplicate
