### ISSUE TITLE
[FEATURE] Show in chat if an attack is a hit.

### ISSUE THREAD

**Issue by noreaga** [MangoFVTT/fvtt-ready-set-roll-5e#338] opened 2024-02-14 05:16 UTC
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, just a QoL feature.

**Describe the solution you'd like**
See Additional context for more information

**Describe alternatives you've considered**
Manually rolling attacks and damage.

**Additional context**

So the new 3.0 system shows your selected target's AC and if you were able to hit with an attack roll. The current update on your module does not show that like the new default DND 5e 3.0 rolling system does. Is this possible to add?

This is what rolls look like without your module enabled (using default 3.0 rolling):

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/29528180/da2ea206-c030-4f70-a43c-3ac8ffb6cae6)

And here it is with Ready Set Roll: 

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/29528180/da4375ca-78f0-4b81-8360-abbea97a9ad7)

Notice the first one shows the target's AC and it's green if it hits, red if it misses.

**Comment by MangoFVTT** [comment] 2024-02-14 08:05
Issue is a duplicate of #318 and has already been resolved in version 3.0.2, please update your RSR module to the latest version.

**Comment by MangoFVTT** [comment] 2024-02-14 08:12
Actually my bad, there appears to have been a regression of this bug in 3.0.4, re-opening to investigate.

**Comment by MangoFVTT** [comment] 2024-02-14 08:24
Issue is now resolved (again) and will be in the next release.

**Closed by MangoFVTT** 2024-02-14 08:24 UTC
