### ISSUE TITLE
[BUG] Third dice during simultaneous rolling (advantage or disadvantage)

### ISSUE THREAD

**Issue by DragonHale** [MangoFVTT/fvtt-ready-set-roll-5e#477] opened 2024-08-12 00:48 UTC
**Description**
When rolling for advantage or disadvantage, there is a third roll of the dice that shouldn't be there (none of us have elven accuracy).

**Steps to Reproduce**
1. Roll for advantage or disadvantage with simultaneous rolls (shift or ctrl commands to roll, or vanilla adv/dis roll)
2. Watch three dice being rolled for the attack (easier to watch if you have manual rolls enabled, as you get three requests for the roll). If Dice so nice happens to work, you will see three dice on the screen instead of two. The third die is a little delayed.
3. The third roll doesn't seem to be taken into account for the attack, but it disrupts the session a lot during manual rolling.

**Versions**
 - Module: 3.1.4
 - dnd5e: 3.3.1
 - Foundry: 12.330

**Other Modules**
I'm also using dice so nice 5.0.5 and the 3D dice rarely display. I've seen other issues opened for this bug so not reporting it separately.

**Comment by MangoFVTT** [comment] 2024-08-12 07:16
I haven't been able to reproduce this error on my end. Enabling/disabling elven accuracy seems to be working exactly as intended and only printing 3 rolls when rolling advantage on an appropriate check. Even enabling Always Roll Multiple Dice has not printed 3 dice at wrong moments. This also makes sense because RSR is not the one that is deciding whether Elven Accuracy should be applied to the roll any longer, it is handled by the base system, which does not have the issue afaik.

![image](https://github.com/user-attachments/assets/92f512e1-c665-471a-8748-c1af7a8b7cf3)

Can you ensure 100% that there is no effect or anything similar that is giving Elven Accuracy? Or that you are not using ANY roller module aside from RSR?

**Comment by MangoFVTT** [comment] 2024-08-13 09:04
Ahh think the problem is with the Manual Rolls input, because that is the only thing you are doing differently than me. I suspect RSR's vanilla message processing doesn't interact very well with the manual roll result input prompts because it's not something that I've ever tested since I don't use it. If you disable manual rolls it will probably work as expected until I figure out a fix

**Comment by MangoFVTT** [comment] 2024-08-13 09:27
Issue should be fixed and will be in the next release.

NOTE: if you are using Always Roll Multiple Dice along with Manual Rolls, you'll still get 2 prompts to fill in (though the AMOUNT of dice now will be correct). This is unavoidable because dnd5e doesn't really support the notion of rolling multiple dice always. However, the prompts now should have the appropriate number of fields to fill in instead of having extras.

**Closed by MangoFVTT** 2024-08-13 09:27 UTC
Labels: bug
