### ISSUE TITLE
[FEATURE/BUG?] Active effect button doesnt appear for players that arent the owner.

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#157] opened 2023-02-07 20:24 UTC
First of all, thanks for your work so far on this module and its features,

**Is your feature request related to a problem? Please describe.**
When a player casts Bless they can apply the effect to themselves but others cant get the effect unless the dm applies it for them.

**Describe the solution you'd like**
either allow everyone to see and apply the button or allow effects to be applied to targeted tokens and not.

**Describe alternatives you've considered**
not using the active effect buttons but do all of this using [DF Convenient Effects](https://github.com/DFreds/dfreds-convenient-effects)

**Comment by OxTailSafu** [comment] 2023-02-08 01:23
Can confirm that even when you use the active effect button that it remains hidden for others who don't own the actor. It does seem to work however if the dm applies it, so that's good at the least.

**Comment by MangoFVTT** [comment] 2023-02-08 09:11
This appears to be an issue caused by core code of the dnd5e system. It hides all action buttons on chat cards for players that don't have permissions over the chat card (i.e. they created it or they're the GM). So far it's unclear how I can override this or whether it's safe to do so

**Comment by MangoFVTT** [comment] 2023-02-10 13:39
Issue should be fixed and will be in the next release.

**Closed by MangoFVTT** 2023-02-10 13:39 UTC
