### ISSUE TITLE
[BUG] Players Cannot Apply Damage To Their Own Tokens Via Chat Cards

### ISSUE THREAD

**Issue by GameCrazed** [MangoFVTT/fvtt-ready-set-roll-5e#403] opened 2024-03-07 23:26 UTC
**Description**
In my games I've always allowed the players to apply damage to their own tokens. In our session tonight we found that this functionality has been lost/disabled? Is it possible to re-introduce it? We've also noticed that player damage resistances/immunities don't apply to the automatic resistance/immunity calculations that take place when applying damage from the chat cards.

**Steps to Reproduce**
1. Roll attack & damage for an NPC as the GM.
2. As the player, select a token you own (ie the player character) and hover over the damage in the chat card.
3. See no options to apply the damage appear.

Additionally from here:
4. As the GM, select that player's token and apply the damage via the 'x1' option.
5. See that resistances and immunities for bludgeoning, piercing, and slashing (I haven't tested with other damage types) is ignored and the full damage is instead applied.
Edit: see my 2nd comment below (one with pics) regarding this bit. I think this may be down to AEs not working properly so possibly not relevant to this module?

**Versions**
 - Module: [3.0.13]
 - dnd5e: [3.0.4]
 - Foundry: [11.315]

**Other Modules**
Tested without any other modules enabled and the issue persists.

**Comment by maxobremer** [comment] 2024-03-08 15:32
Tested this myself in my main world and a test world with no other modules and did not have the same issues at all. player can apply damage as intended and resistance and immunities still work as tested. Maybe double check your settings?

**Versions**
- Module: [3.0.13]
- dnd5e: [3.0.4]
- Foundry: [11.315]

**Comment by GameCrazed** [comment] 2024-03-08 16:22
Interesting... I'll check the settings. Are there any user permission settings you'd recommend or should they not matter here?

I did both my tests on a Forge hosted instance so I'll test on a blank locally hosted world when I get home tonight.

Thanks for the speedy response btw

**Comment by GameCrazed** [comment] 2024-03-08 18:33
So testing it locally in a brand new world, with only this module enabled, I still get the error.
If I make an attack roll as 'Renlar' as one player (doesn't seem to care if it's the GM or not), I can hover over my own attack and see the options (as the GM these options appear for all damages etc since I guess they have ownership of all actors?):
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/7393464/fb7f900d-1125-41ff-8674-30e358d3a288)
But if I then go to the other player's account and hover over the damage field none of those options appear:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/7393464/be07bf61-eb20-45c2-8d66-84f6aa38e6bf)

I can expand the damage box and hover over the dice rolls and its the same story.

I have however figured out what the issue regarding damage immunity and resistance is. If a damage immunity/resistance is granted by an Active Effect it seems to bypass the calculations. I tested this by granting slashing resistance to Mia manually which resulted in the aforementioned attack dealing 5 damage. Toggle rage on and let the AE apply the slashing resistance instead? Full damage. Given this I'm not sure whether the issue is with this module or the 5e module in general.

**Comment by GameCrazed** [comment] 2024-03-12 18:37
I've since tried a few more ideas to try and resolve this issue but all of it came up empty. All I can say is that on a brand new world, with only this module running, on the versions stated in my initial ticket. If I roll an attack as one player, and then log in as another player, it will not allow me to apply the damage from that player's attack to my token. This also happens when making attacks as the GM, on both player and npc characters, and the game's pause-state seems to have no effect on this.

Not sure how maxobremer was able to get it working on a clean world unless I'm missing something in the settings. But in my clean test world, at the time of testing, I hadn't so much as opened them, so they're guaranteed to be in whatever the default state is. And now that I've looked through them, nothing is jumping out at me as an obvious fix.

This is happening on my Forge-hosted campaign world, and also on my locally-hosted test world, so I don't think it's something specific to my system, though perhaps like I said there's some config I'm missing. Oh, and I've tested this using both Chrome and Firefox, both exhibiting the same issue, so I don't think it's browser related either

If there's anything I can do to help debugging this weird issue just let me know.

**Comment by crash1115** [comment] 2024-03-15 23:19
I've also experienced this and seen others experience, across multiple worlds.

My test world was running Foundry 315, dnd5e 3.0.4, RSR 3.0.13. No other modules.

I'm not sure exactly which versions the other world was using (I'm a player in this game not a GM), but it was definitely after the dnd5e 3.x updates. Modules were definitely enabled there, but I don't know off the top of my head which they were.

**Comment by denis-kralj** [comment] 2024-03-17 00:06
> I've also experienced this and seen others experience, across multiple worlds.
> 
> My test world was running Foundry 315, dnd5e 3.0.4, RSR 3.0.13. No other modules.
> 
> I'm not sure exactly which versions the other world was using (I'm a player in this game not a GM), but it was definitely after the dnd5e 3.x updates. Modules were definitely enabled there, but I don't know off the top of my head which they were.
> 
> EDIT: Forgot to mention, if you have the RSR setting "Always Show Apply Buttons" enabled, players can apply damage and healing just fine. It's just that the buttons don't display when they're set to appear on hover.

Came here the comment on this, it is as @crash1115 describes it. If in settings it says it only shows up on hover, the players only get hover buttons to show up on their own rolls, not on rolls for actors they don't own. Setting the buttons to always show is a workaround for the issue, since then all of them show up all the time.

**Comment by GameCrazed** [comment] 2024-03-17 10:00
Thanks to both of you, that does indeed work! Can't believe I never tried that setting in my testing (or maybe I did, fudged the test, and just forgot). Either way you both just saved me a world of headaches trying to wrangle my gaggle of players. Here's hoping this bug gets resolved quickly though as I believe the default settings _are_ to have the buttons dynamically appear and I'd hate to see people fall off this module for something so small.

**Comment by MangoFVTT** [comment] 2024-03-22 09:49
Issue has been resolved and will be in the next release. Much thanks for the thorough investigations <3

**Closed by MangoFVTT** 2024-03-22 09:49 UTC
Labels: bug
